### ISSUE TITLE
Docker upgrade failed using "docker compose -f - --profile demo up --pull always"

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#320]
```
~/r/f/dbsp (main)> git log -n1
commit f6d25b110b91462886c2fcd12c828234f933f0c4 (HEAD -> main, origin/main, origin/HEAD)
Author: Mihai Budiu <mbudiu@feldera.com>
Date:   Thu Jul 6 10:04:41 2023 -0700

    [SQL] Support for time operations in JIT compiler (#311)
    
    * [SQL] Support for time operations in JIT compiler
    * [sql] Correctly assign tuple temporaries
    Signed-off-by: Mihai Budiu <mbudiu@feldera.com>
    
~/r/f/dbsp (main)> cat ./deploy/docker-compose.yml | docker compose -f - --profile demo up --pull always

...

Attaching to dbsp-db-1, dbsp-dbsp-1, dbsp-demo-1, dbsp-redpanda-1

...

dbsp-dbsp-1      | Error: DB schema migration error: 'applied migration V0__ddl_base is different than filesystem one V0__ddl_base'
dbsp-dbsp-1      | 
dbsp-dbsp-1      | Stack backtrace:
dbsp-dbsp-1      |    0: std::thread::local::LocalKey<T>::with
dbsp-dbsp-1      |    1: tokio::task::local::LocalSet::run_until::{{closure}}
dbsp-dbsp-1      |    2: tokio::runtime::scheduler::current_thread::Context::enter
dbsp-dbsp-1      |    3: tokio::runtime::context::scoped::Scoped<T>::set
dbsp-dbsp-1      |    4: tokio::runtime::context::set_scheduler
dbsp-dbsp-1      |    5: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
dbsp-dbsp-1      |    6: tokio::runtime::context::runtime::enter_runtime
dbsp-dbsp-1      |    7: tokio::runtime::runtime::Runtime::block_on
dbsp-dbsp-1      |    8: dbsp_pipeline_manager::main
dbsp-dbsp-1      |    9: std::sys_common::backtrace::__rust_begin_short_backtrace
dbsp-dbsp-1      |   10: std::rt::lang_start::{{closure}}
dbsp-dbsp-1      |   11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
dbsp-dbsp-1      |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
dbsp-dbsp-1      |       std::panicking::try::do_call
dbsp-dbsp-1      |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
dbsp-dbsp-1      |       std::panicking::try
dbsp-dbsp-1      |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
dbsp-dbsp-1      |       std::panic::catch_unwind
dbsp-dbsp-1      |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
dbsp-dbsp-1      |       std::rt::lang_start_internal::{{closure}}
dbsp-dbsp-1      |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
dbsp-dbsp-1      |       std::panicking::try::do_call
dbsp-dbsp-1      |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
dbsp-dbsp-1      |       std::panicking::try
dbsp-dbsp-1      |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
dbsp-dbsp-1      |       std::panic::catch_unwind
dbsp-dbsp-1      |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
dbsp-dbsp-1      |       std::rt::lang_start_internal
dbsp-dbsp-1      |              at ./rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
dbsp-dbsp-1      |   12: main
dbsp-dbsp-1      |   13: <unknown>
dbsp-dbsp-1      |   14: __libc_start_main
dbsp-dbsp-1      |   15: _start
dbsp-dbsp-1 exited with code 1
dbsp-demo-1      | Traceback (most recent call last):
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 10, in map_exceptions
dbsp-demo-1      |     yield
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 100, in connect_tcp
dbsp-demo-1      |     sock = socket.create_connection(
dbsp-demo-1      |   File "/usr/lib/python3.10/socket.py", line 824, in create_connection
dbsp-demo-1      |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
dbsp-demo-1      |   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
dbsp-demo-1      |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
dbsp-demo-1      | socket.gaierror: [Errno -2] Name or service not known
dbsp-demo-1      | 
dbsp-demo-1      | The above exception was the direct cause of the following exception:
dbsp-demo-1      | 
dbsp-demo-1      | Traceback (most recent call last):
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
dbsp-demo-1      |     yield
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 218, in handle_request
dbsp-demo-1      |     resp = self._pool.handle_request(req)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
dbsp-demo-1      |     raise exc
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
dbsp-demo-1      |     response = connection.handle_request(request)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 92, in handle_request
dbsp-demo-1      |     raise exc
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 69, in handle_request
dbsp-demo-1      |     stream = self._connect(request)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 117, in _connect
dbsp-demo-1      |     stream = self._network_backend.connect_tcp(**kwargs)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 99, in connect_tcp
dbsp-demo-1      |     with map_exceptions(exc_map):
dbsp-demo-1      |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
dbsp-demo-1      |     self.gen.throw(typ, value, traceback)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
dbsp-demo-1      |     raise to_exc(exc) from exc
dbsp-demo-1      | httpcore.ConnectError: [Errno -2] Name or service not known
dbsp-demo-1      | 
dbsp-demo-1      | The above exception was the direct cause of the following exception:
dbsp-demo-1      | 
dbsp-demo-1      | Traceback (most recent call last):
dbsp-demo-1      |   File "/demo/project_demo00-SecOps/run.py", line 95, in <module>
dbsp-demo-1      |     run_demo(
dbsp-demo-1      |   File "/demo/../demo/__init__.py", line 57, in run_demo
dbsp-demo-1      |     execute(dbsp_url, actions, name, code_file,
dbsp-demo-1      |   File "/demo/../demo/__init__.py", line 7, in execute
dbsp-demo-1      |     dbsp = DBSPConnection(dbsp_url)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/dbsp/connection.py", line 20, in __init__
dbsp-demo-1      |     list_programs.sync_detailed(client = self.api_client).unwrap("Failed to fetch program list from the DBSP server")
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/dbsp_api_client/api/program/list_programs.py", line 76, in sync_detailed
dbsp-demo-1      |     response = httpx.request(
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_api.py", line 100, in request
dbsp-demo-1      |     return client.request(
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 814, in request
dbsp-demo-1      |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 901, in send
dbsp-demo-1      |     response = self._send_handling_auth(
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 929, in _send_handling_auth
dbsp-demo-1      |     response = self._send_handling_redirects(
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 966, in _send_handling_redirects
dbsp-demo-1      |     response = self._send_single_request(request)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1002, in _send_single_request
dbsp-demo-1      |     response = transport.handle_request(request)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 217, in handle_request
dbsp-demo-1      |     with map_httpcore_exceptions():
dbsp-demo-1      |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
dbsp-demo-1      |     self.gen.throw(typ, value, traceback)
dbsp-demo-1      |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
dbsp-demo-1      |     raise mapped_exc(message) from exc
dbsp-demo-1      | httpx.ConnectError: [Errno -2] Name or service not known
dbsp-demo-1 exited with code 1
dbsp-db-1        | 2023-07-07 00:27:19.293 UTC [27] LOG:  checkpoint starting: time
dbsp-db-1        | 2023-07-07 00:27:19.823 UTC [27] LOG:  checkpoint complete: wrote 8 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.514 s, sync=0.004 s, total=0.532 s; sync files=5, longest=0.002 s, average=0.001 s; distance=0 kB, estimate=0 kB
dbsp-demo-1 exited with code 1
dbsp-db-1        | 2023-07-07 00:27:19.293 UTC [27] LOG:  checkpoint starting: time
dbsp-db-1        | 2023-07-07 00:27:19.823 UTC [27] LOG:  checkpoint complete: wrote 8 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.514 s, sync=0.004 s, total=0.532 s; sync files=5, longest=0.002 s, average=0.001 s; distance=0 kB, estimate=0 kB
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 4/4
 ✔ Container dbsp-demo-1      Stopped
 ✔ Container dbsp-redpanda-1  Stopped
 ✔ Container dbsp-dbsp-1      Stopped
 ✔ Container dbsp-db-1        Stopped
canceled

**Comment by ryzhyk** [comment]
A recent PR changed DB schema without using the upgrade mechanism. You need to re-create the DB (all projects will be gone): use `--renew-anon-volumes`.

**Comment by mohsinbeg** [comment]
> A recent PR changed DB schema without using the upgrade mechanism. You need to re-create the DB (all projects will be gone): pass `--renew-anon-volumes` to `docker compose`.

It didn't work.

```
~/r/f/dbsp (main)> cat ./deploy/docker-compose.yml | docker compose -f - --profile demo up --pull always --renew-anon-volumes

WARN[0000] The "SECOPS_DEMO_ARGS" variable is not set. Defaulting to a blank string. 
[+] Running 4/4
 ✔ db Pulled                                                                                                                                                                          1.5s 
 ✔ redpanda Pulled                                                                                                                                                                    1.7s 
 ✔ dbsp Pulled                                                                                                                                                                        1.2s 
 ✔ demo Pulled                                                                                                                                                                        1.2s 
[+] Building 0.0s (0/0)                                                                                                                                                                    
[+] Running 4/0
 ✔ Container dbsp-redpanda-1  Created                                                                                                                                                 0.0s 
 ✔ Container dbsp-db-1        Created                                                                                                                                                 0.0s 
 ✔ Container dbsp-dbsp-1      Created                                                                                                                                                 0.0s 
 ✔ Container dbsp-demo-1      Created                                                                                                                                                 0.0s 
Attaching to dbsp-db-1, dbsp-dbsp-1, dbsp-demo-1, dbsp-redpanda-1

...

dbsp-dbsp-1      | 2023-07-07 00:43:48 INFO [manager] NOTICE: relation "refinery_schema_history" already exists, skipping
dbsp-dbsp-1      | Error: DB schema migration error: 'applied migration V0__ddl_base is different than filesystem one V0__ddl_base'
dbsp-dbsp-1      | 
dbsp-dbsp-1      | Stack backtrace:

...

dbsp-demo-1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
```

**Comment by mohsinbeg** [comment]
> A recent PR changed DB schema without using the upgrade mechanism. You need to re-create the DB (all projects will be gone): pass `--renew-anon-volumes` to `docker compose`.

@lalithsuresh we should also add an upgrade validation with our builds. For example, start docker with previous published (or labelled) containers, build containers with current head and attempt a live upgrade.

**Comment by lalithsuresh** [comment]
@mohsinbeg you also need `--force-recreate-containers`.

**Comment by mohsinbeg** [comment]
> @mohsinbeg you also need `--force-recreate-containers`.

It worked. Closing the issue.
