### ISSUE TITLE
Demo container only brings up the secops demo

### ISSUE THREAD

**Issue by blp** [feldera/dbsp#424]
The demo container supports several demos but the command that it runs at launch only creates and populates the secops demo. We should make all of them available.

**Comment by Karakatiza666** [comment]
To run the demo containers:
`docker compose --profile demo up`
To open a terminal inside the demo container:
`docker exec --workdir / -it deploy-demo-1 bash`
Try preparing one of the demos:
`cd /demo/project_demo01-TimeSeriesEnrich && python3 run.py --dbsp_url http://dbsp:8080 --actions prepare create compile`
Current error:
```
Traceback (most recent call last):
  File "/demo/project_demo01-TimeSeriesEnrich/run.py", line 70, in <module>
    run_demo("Time Series Enrichment", os.path.join(
  File "/demo/../demo/__init__.py", line 57, in run_demo
    execute(dbsp_url, actions, name, code_file,
  File "/demo/../demo/__init__.py", line 9, in execute
    program = dbsp.create_or_replace_program(
  File "/usr/local/lib/python3.10/dist-packages/dbsp/connection.py", line 61, in create_or_replace_program
    return self.create_program_inner(name = name, sql_code = sql_code, description = description, replace = True)
  File "/usr/local/lib/python3.10/dist-packages/dbsp/connection.py", line 72, in create_program_inner
    new_program_response = new_program.sync_detailed(client = self.api_client, json_body=request).unwrap("Failed to create a program")
  File "/usr/local/lib/python3.10/dist-packages/feldera_api_client/api/programs/new_program.py", line 85, in sync_detailed
    return _build_response(client=client, response=response)
  File "/usr/local/lib/python3.10/dist-packages/feldera_api_client/api/programs/new_program.py", line 53, in _build_response
    parsed=_parse_response(client=client, response=response),
  File "/usr/local/lib/python3.10/dist-packages/feldera_api_client/api/programs/new_program.py", line 37, in _parse_response
    response_409 = ErrorResponse.from_dict(response.json())
  File "/usr/local/lib/python3.10/dist-packages/feldera_api_client/models/error_response.py", line 51, in from_dict
    details = ErrorResponseDetails.from_dict(d.pop("details"))
  File "/usr/local/lib/python3.10/dist-packages/feldera_api_client/models/error_response_details.py", line 26, in from_dict
    d = src_dict.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```
Error only occurs when `prepare` action is executed.

Once the prepare issue is fixed, the following change to deploy/docker-compose.yml will prepare all the demos on startup:
```
  demo:
    ...
    command: >
      bash -c "cd /demo/project_demo00-SecOps           && python3 run.py --dbsp_url http://dbsp:8080 --actions prepare create compile $${SECOPS_DEMO_ARGS}
               cd /demo/project_demo01-TimeSeriesEnrich && python3 run.py --dbsp_url http://dbsp:8080 --actions prepare create compile
               cd /demo/project_demo02-FraudDetection   && python3 run.py --dbsp_url http://dbsp:8080 --actions prepare create compile
               cd /demo/project_demo03-GreenTrip        && python3 run.py --dbsp_url http://dbsp:8080 --actions prepare create compile
               cd /demo/project_demo04-SimpleSelect     && python3 run.py --dbsp_url http://dbsp:8080 --actions prepare create compile"
```
or
```
  demo:
    ...
    command: >
      bash -c "DBSP_MANAGER=\"http://dbsp:8080\" demo/prepare_demo_data.sh && DBSP_MANAGER=\"http://dbsp:8080\" demo/create_demo_projects.sh"
```

**Comment by blp** [comment]
@ryzhyk I think we're just publishing a single demo. Do we want to drop this issue?

**Comment by ryzhyk** [comment]
yep.
